/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Mon May 13 08:48:24 2019. */

#ifndef PB_ISTAR_PB_H_INCLUDED
#define PB_ISTAR_PB_H_INCLUDED
#include "src/pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Frame {
    struct _Header *header;
    struct _iSTAR *istar;
    struct _DPM *dpm;
    struct _SOFAR *sofar;
    struct _MFM *mfm;
/* @@protoc_insertion_point(struct:Frame) */
} Frame;

typedef struct _Comunication {
    int32_t WIFI;
    int32_t Ethernet;
    int32_t GSM;
/* @@protoc_insertion_point(struct:Comunication) */
} Comunication;

typedef struct _DPM {
    float A1;
    float A2;
    float A3;
    float A4;
    float A5;
    float A6;
    float A7;
    float A8;
    float A9;
    float A10;
    float A11;
    float A12;
    float A13;
    float A14;
    float A15;
    float A16;
    float A17;
    float A18;
    float A19;
    float A20;
    float A21;
    float A22;
    float A23;
    float A24;
    float A25;
    float A26;
    float A27;
    float A28;
    float A29;
    float A30;
    float A31;
    uint32_t A32;
    uint32_t A33;
    uint32_t A34;
    uint32_t A35;
    uint32_t A36;
    uint32_t A37;
    uint32_t A38;
    uint32_t status;
/* @@protoc_insertion_point(struct:DPM) */
} DPM;

typedef struct _MFM {
    float A1;
    float A2;
    float A3;
    float A4;
    float A5;
    float A6;
    float A7;
    float A8;
    float A9;
    float A10;
    float A11;
    float A12;
    float A13;
    float A14;
    float A15;
    float A16;
    float A17;
    float A18;
    float A19;
    float A20;
    float A21;
    float A22;
    float A23;
    float A24;
    float A25;
    float A26;
    float A27;
    float A28;
    float A29;
    float A30;
    float A31;
    float A32;
    uint32_t status;
/* @@protoc_insertion_point(struct:MFM) */
} MFM;

typedef struct _SOFAR {
    uint32_t A1;
    uint32_t A2;
    uint32_t A3;
    uint32_t A4;
    uint32_t A5;
    uint32_t A6;
    float A7;
    float A8;
    float A9;
    float A10;
    float A11;
    float A12;
    float A13;
    float A14;
    float A15;
    float A16;
    float A17;
    float A18;
    float A19;
    float A20;
    float A21;
    float A22;
    float A23;
    float A24;
    uint32_t A25;
    int32_t A26;
    int32_t A27;
    uint32_t A28;
    uint32_t A29;
    uint32_t A30;
    uint32_t A31;
    uint32_t A32;
    uint32_t A33;
    uint32_t A34;
    uint32_t A35;
    uint32_t A36;
    uint32_t A37;
    uint32_t A38;
    uint32_t status;
/* @@protoc_insertion_point(struct:SOFAR) */
} SOFAR;

typedef struct _iSTAR {
    int32_t A1;
    bool A2;
    uint32_t A3;
    uint32_t A4;
    bool A5;
    bool A6;
    bool A7;
    uint32_t A8;
    uint32_t A9;
    uint32_t A10;
    uint32_t A11;
    uint32_t A12;
    uint32_t A13;
    uint32_t A14;
    uint32_t A15;
    char A16[50];
    uint32_t A17;
    uint32_t A18;
    uint32_t A19;
    uint32_t A20;
    uint32_t A21;
    uint32_t A22;
    char A23[50];
    char A24[50];
    char A25[50];
    char A26[50];
    char A27[50];
    char A28[50];
    uint32_t A29;
    uint32_t A30;
    uint32_t A31;
    uint32_t A32;
    uint32_t A33;
    uint32_t A34;
    uint32_t A35;
    uint32_t A36;
    char A37[50];
    uint32_t status;
/* @@protoc_insertion_point(struct:iSTAR) */
} iSTAR;

typedef struct _Header {
    char Serial[50];
    uint32_t Reset_Count;
    uint32_t Free_Ram;
    Comunication Com;
    char Version[50];
    float INTemp;
    char Debug[50];
/* @@protoc_insertion_point(struct:Header) */
} Header;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Comunication_init_default                {0, 0, 0}
#define Header_init_default                      {"", 0, 0, Comunication_init_default, "", 0, ""}
#define iSTAR_init_default                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, "", "", "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define DPM_init_default                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SOFAR_init_default                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MFM_init_default                         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Frame_init_default                       {NULL, NULL, NULL, NULL, NULL}
#define Comunication_init_zero                   {0, 0, 0}
#define Header_init_zero                         {"", 0, 0, Comunication_init_zero, "", 0, ""}
#define iSTAR_init_zero                          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, "", "", "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define DPM_init_zero                            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SOFAR_init_zero                          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MFM_init_zero                            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Frame_init_zero                          {NULL, NULL, NULL, NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define Frame_header_tag                         1
#define Frame_istar_tag                          2
#define Frame_dpm_tag                            3
#define Frame_sofar_tag                          4
#define Frame_mfm_tag                            5
#define Comunication_WIFI_tag                    1
#define Comunication_Ethernet_tag                2
#define Comunication_GSM_tag                     3
#define DPM_status_tag                           39
#define DPM_A1_tag                               1
#define DPM_A2_tag                               2
#define DPM_A3_tag                               3
#define DPM_A4_tag                               4
#define DPM_A5_tag                               5
#define DPM_A6_tag                               6
#define DPM_A7_tag                               7
#define DPM_A8_tag                               8
#define DPM_A9_tag                               9
#define DPM_A10_tag                              10
#define DPM_A11_tag                              11
#define DPM_A12_tag                              12
#define DPM_A13_tag                              13
#define DPM_A14_tag                              14
#define DPM_A15_tag                              15
#define DPM_A16_tag                              16
#define DPM_A17_tag                              17
#define DPM_A18_tag                              18
#define DPM_A19_tag                              19
#define DPM_A20_tag                              20
#define DPM_A21_tag                              21
#define DPM_A22_tag                              22
#define DPM_A23_tag                              23
#define DPM_A24_tag                              24
#define DPM_A25_tag                              25
#define DPM_A26_tag                              26
#define DPM_A27_tag                              27
#define DPM_A28_tag                              28
#define DPM_A29_tag                              29
#define DPM_A30_tag                              30
#define DPM_A31_tag                              31
#define DPM_A32_tag                              32
#define DPM_A33_tag                              33
#define DPM_A34_tag                              34
#define DPM_A35_tag                              35
#define DPM_A36_tag                              36
#define DPM_A37_tag                              37
#define DPM_A38_tag                              38
#define MFM_status_tag                           33
#define MFM_A1_tag                               1
#define MFM_A2_tag                               2
#define MFM_A3_tag                               3
#define MFM_A4_tag                               4
#define MFM_A5_tag                               5
#define MFM_A6_tag                               6
#define MFM_A7_tag                               7
#define MFM_A8_tag                               8
#define MFM_A9_tag                               9
#define MFM_A10_tag                              10
#define MFM_A11_tag                              11
#define MFM_A12_tag                              12
#define MFM_A13_tag                              13
#define MFM_A14_tag                              14
#define MFM_A15_tag                              15
#define MFM_A16_tag                              16
#define MFM_A17_tag                              17
#define MFM_A18_tag                              18
#define MFM_A19_tag                              19
#define MFM_A20_tag                              20
#define MFM_A21_tag                              21
#define MFM_A22_tag                              22
#define MFM_A23_tag                              23
#define MFM_A24_tag                              24
#define MFM_A25_tag                              25
#define MFM_A26_tag                              26
#define MFM_A27_tag                              27
#define MFM_A28_tag                              28
#define MFM_A29_tag                              29
#define MFM_A30_tag                              30
#define MFM_A31_tag                              31
#define MFM_A32_tag                              32
#define SOFAR_status_tag                         39
#define SOFAR_A1_tag                             1
#define SOFAR_A2_tag                             2
#define SOFAR_A3_tag                             3
#define SOFAR_A4_tag                             4
#define SOFAR_A5_tag                             5
#define SOFAR_A6_tag                             6
#define SOFAR_A7_tag                             7
#define SOFAR_A8_tag                             8
#define SOFAR_A9_tag                             9
#define SOFAR_A10_tag                            10
#define SOFAR_A11_tag                            11
#define SOFAR_A12_tag                            12
#define SOFAR_A13_tag                            13
#define SOFAR_A14_tag                            14
#define SOFAR_A15_tag                            15
#define SOFAR_A16_tag                            16
#define SOFAR_A17_tag                            17
#define SOFAR_A18_tag                            18
#define SOFAR_A19_tag                            19
#define SOFAR_A20_tag                            20
#define SOFAR_A21_tag                            21
#define SOFAR_A22_tag                            22
#define SOFAR_A23_tag                            23
#define SOFAR_A24_tag                            24
#define SOFAR_A25_tag                            25
#define SOFAR_A26_tag                            26
#define SOFAR_A27_tag                            27
#define SOFAR_A28_tag                            28
#define SOFAR_A29_tag                            29
#define SOFAR_A30_tag                            30
#define SOFAR_A31_tag                            31
#define SOFAR_A32_tag                            32
#define SOFAR_A33_tag                            33
#define SOFAR_A34_tag                            34
#define SOFAR_A35_tag                            35
#define SOFAR_A36_tag                            36
#define SOFAR_A37_tag                            37
#define SOFAR_A38_tag                            38
#define iSTAR_status_tag                         38
#define iSTAR_A1_tag                             1
#define iSTAR_A2_tag                             2
#define iSTAR_A3_tag                             3
#define iSTAR_A4_tag                             4
#define iSTAR_A5_tag                             5
#define iSTAR_A6_tag                             6
#define iSTAR_A7_tag                             7
#define iSTAR_A8_tag                             8
#define iSTAR_A9_tag                             9
#define iSTAR_A10_tag                            10
#define iSTAR_A11_tag                            11
#define iSTAR_A12_tag                            12
#define iSTAR_A13_tag                            13
#define iSTAR_A14_tag                            14
#define iSTAR_A15_tag                            15
#define iSTAR_A16_tag                            16
#define iSTAR_A17_tag                            17
#define iSTAR_A18_tag                            18
#define iSTAR_A19_tag                            19
#define iSTAR_A20_tag                            20
#define iSTAR_A21_tag                            21
#define iSTAR_A22_tag                            22
#define iSTAR_A23_tag                            23
#define iSTAR_A24_tag                            24
#define iSTAR_A25_tag                            25
#define iSTAR_A26_tag                            26
#define iSTAR_A27_tag                            27
#define iSTAR_A28_tag                            28
#define iSTAR_A29_tag                            29
#define iSTAR_A30_tag                            30
#define iSTAR_A31_tag                            31
#define iSTAR_A32_tag                            32
#define iSTAR_A33_tag                            33
#define iSTAR_A34_tag                            34
#define iSTAR_A35_tag                            35
#define iSTAR_A36_tag                            36
#define iSTAR_A37_tag                            37
#define Header_Serial_tag                        1
#define Header_Reset_Count_tag                   2
#define Header_Free_Ram_tag                      3
#define Header_Com_tag                           4
#define Header_Version_tag                       5
#define Header_INTemp_tag                        6
#define Header_Debug_tag                         7

/* Struct field encoding specification for nanopb */
extern const pb_field_t Comunication_fields[4];
extern const pb_field_t Header_fields[8];
extern const pb_field_t iSTAR_fields[39];
extern const pb_field_t DPM_fields[40];
extern const pb_field_t SOFAR_fields[40];
extern const pb_field_t MFM_fields[34];
extern const pb_field_t Frame_fields[6];

/* Maximum encoded size of messages (where known) */
#define Comunication_size                        33
#define Header_size                              208
#define iSTAR_size                               608
#define DPM_size                                 227
#define SOFAR_size                               250
#define MFM_size                                 184
/* Frame_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ISTAR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
